### ISSUE TITLE
UI/UX design

### ISSUE THREAD

**Issue by abogaziah** [lighthousetanta/lighthouse#5]
@M-Yahia2011 will present user interface and user experience design this week

**Comment by M-Yahia2011** [comment]
# First Prototype
![Login](https://user-images.githubusercontent.com/62570243/106441256-808a3780-6482-11eb-9d47-5d8ec5fd7227.png)
#
![Sign-up](https://user-images.githubusercontent.com/62570243/106441343-9ac41580-6482-11eb-8aba-2024b84e2060.png)
#
![Home](https://user-images.githubusercontent.com/62570243/106441333-9861bb80-6482-11eb-89d1-111f39c10e1e.png)
#
![Add a Missing Person](https://user-images.githubusercontent.com/62570243/106441325-94ce3480-6482-11eb-9a05-222629bf24b8.png)
